services:
  - type: web
    name: verbo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
